### ISSUE TITLE
how to use?

### ISSUE THREAD

**Issue by apporoad** [abe-taylor-970/CombineTiff#1]

**Comment by abe-taylor-970** [comment]
This is a Java program. The main method is in the CombineTiff.java file. First, the file path should be changed where the File object is created in CombineTiff.java. Then, the program can be compiled and run.

**Comment by abe-taylor-970** [comment]
I didn't have the most recent version uploaded, but now I have uploaded it, as well as updating the README on how to use the files. Hope this helps!

**Comment by apporoad** [comment]
good job
thx
